TECH buggy version which works incorrectly with big negative numbers
RuslanTyan/phpcourse pull request #1
Opened 2022-03-10 20:13 UTC by RuslanTyan

2022-03-11 04:58 UTC, ova777 requested changes

2022-03-11 04:58 UTC, ova777 commented on src/Solution.php
> +    if (!isBynaryString($num1) or !isBynaryString($num2)) {
Явного указания в PSR использовать `&&` и `||` вместо `and` и `or` вроде нет, но все-таки все используют именно `&&` и `||`. Операторы `and` и `or` нужны если есть сложное составное условие, т.к. у них другой приоритет относительно `&&` и `||`, но в таком случае, опять же, лучше разрулить это используя скобки, для лучшей читаемости.
В общем я бы вообще не стал пользоваться `and` и `or`, т.к. это выглядит как legacy.

2022-03-11 04:58 UTC, ova777 commented on src/Solution.php
> +    //
Эта и две предыдущие пустые строки портят весь вид ))

2022-03-11 20:26 UTC, RuslanTyan commented on src/Solution.php
> +    if (!isBynaryString($num1) or !isBynaryString($num2)) {
fixed

2022-03-11 20:27 UTC, RuslanTyan commented on src/Solution.php
> +    //
fixed

2022-03-22 04:15 UTC, ova777 requested changes

2022-03-22 04:15 UTC, ovaunit commented on src/Solution.php
> +<?php
У тебя файлы в других заданиях называются PowerOfThree, Fibonacci, AddDigits, и т.д., а тут просто Solution/OldSolution, переименовать бы для семантичности.

2022-03-22 04:15 UTC, ova777 commented on src/OldSolution.php
> +        return 'Error: non binary arguments';
В случае ошибки я бы предложил возвращать null, а сообщение ты и так выводишь в stdout.
Потому что если ты и в случае ошибки и с валидными данными возвращаешь строку - как понять была ли ошибка?
(ниже аналогично)

2022-03-22 04:15 UTC, ova777 commented on src/OldSolution.php
> +    if (isMaxSizeExceeded($num1)) {
Получается что для каждого числа ты вызываешь isMaxSizeExceeded дважды.
Лучше сначала сохранить эти проверки, и далее уже их использовать.
```
$isNum1SizeExceeded = isMaxSizeExceeded($num1);
```

2022-03-22 19:20 UTC, RuslanTyan commented on src/Solution.php
> +<?php
поправил на BinarySum & BinarySumViaInt

2022-03-22 19:21 UTC, RuslanTyan commented on src/OldSolution.php
> +        return 'Error: non binary arguments';
поправил во всех 3 местах, где выходит с ошибкой - не только '0' или '1', слишком большие аргументы, слишком большая сумма

2022-03-22 19:21 UTC, RuslanTyan commented on src/OldSolution.php
> +    if (isMaxSizeExceeded($num1)) {
поправил

2022-03-25 10:45 UTC, ova777 approved these changes

2022-03-25 11:29 UTC, merged