Rtyan is power of three test 2
RuslanTyan/phpcourse pull request #2
Opened 2022-03-15 19:00 UTC by RuslanTyan

src/Solution.php
Реализуйте функцию isPowerOfThree() которая определяет, является ли переданное число натуральной степенью тройки. Например, число 27 – это третья степень (33), а 81 – четвёртая (34).

<?php

isPowerOfThree(1); // → true (3^0)
isPowerOfThree(3); // → true
isPowerOfThree(4); // → false
isPowerOfThree(9); // → true

2022-03-21 08:34 UTC, ova777 requested changes

2022-03-21 08:34 UTC, ova777 commented on src/PowerOfThree.php
> +        if ($result === $num) return true;
По psr код, относящийся к if/else всегда нужно обарачивать в `{}`, даже если там только один оператор

2022-03-21 09:04 UTC, RuslanTyan commented on src/PowerOfThree.php
> +        if ($result === $num) return true;
fixed

2022-03-22 03:51 UTC, ova777 approved these changes

2022-03-22 04:31 UTC, merged