Fibonacci function test - 3
RuslanTyan/phpcourse pull request #3
Opened 2022-03-15 20:49 UTC by RuslanTyan

Реализуйте функцию fib(), находящую положительные числа Фибоначчи. Аргументом функции является порядковый номер числа.

Формула:

f(0) = 0
f(1) = 1
f(n) = f(n-1) + f(n-2)
Пример:

```
<?php

fib(3); // 2
fib(5); // 5
fib(10); // 55
```

2022-03-15 20:52 UTC, RuslanTyan commented on src/Fibonacci.php
> +$fibonacci = array();
Шторм почему-то показывает
Warning:(5, 1) Unused local variable 'fibonacci'. The value of the variable is not used anywhere.
хотя все работает: 

```
php src/Fibonacci.php
Error: function fib accepts only natural integer index: -1 given/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
NULL
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(0)
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(1)
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(2)
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(5)
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(55)
/Users/rtyan/github/phpcourse/src/Fibonacci.php:35:
int(1548008755920)
```

2022-03-21 08:30 UTC, ova777 requested changes

2022-03-21 08:30 UTC, ova777 commented on src/Fibonacci.php
> +$fibonacci = array();
Потому что он не отслеживает то что ты используешь эту переменную через `global`.
Использовать глобальные переменные ОЧЕНЬ плохо.
Я могу между вызовами fib взять и поменять в `$fibonacci` значения, и fib уже будет работать неправильно.
Я понимаю что ты хотел сделать оптимизацию что бы не было повторных расчетов уже высчитанных ранее значений, но, тем не менее, от глобальной переменной нужно избавиться.
Далее, когда мы переделаем всё это на классы - можно будет сделать private свойство, которое будет выступать хранилищем высчитанных значений.

2022-03-21 08:30 UTC, ova777 commented on src/Fibonacci.php
> +$fibonacci = array();
И еще один момент - `array()` это старая запись (deprecated), давно уже достаточно писать `[]`.

2022-03-21 08:30 UTC, ova777 commented on src/Fibonacci.php
> +    } else {
Здесь не нужно обарачивать код в `else`, т.к. если сработает предыдущий return - до этого кода мы не дойдем.

2022-03-21 09:20 UTC, RuslanTyan commented on src/Fibonacci.php
> +    } else {
кстати, да, шторм подсказывал, в каком-то другом задании я убирал else

2022-03-21 09:20 UTC, RuslanTyan commented on src/Fibonacci.php
> +$fibonacci = array();
fixed

2022-03-21 09:22 UTC, RuslanTyan commented on src/Fibonacci.php
> +            return fib($index - 1) + fib($index - 2);
мне кажется или тут неочевидно и лучше переделать на if'ы ?

2022-03-22 03:55 UTC, ova777 approved these changes

2022-03-22 03:55 UTC, ova777 commented on src/Fibonacci.php
> +            return fib($index - 1) + fib($index - 2);
Да всё очевидно, но с if'ами и ранним возвратом получилась бы меньшая сложность. Я бы сделал
```
if ($index === 0 || $index === 1) {
    return $index;
}
```
И далее то что у тебя в default

2022-03-22 03:55 UTC, ova777 commented on src/Fibonacci.php
> +            return fib($index - 1) + fib($index - 2);
Поэтому если есть желание - переделай, если нет - approve.

2022-03-22 04:32 UTC, merged