isBalanced function test - 5
RuslanTyan/phpcourse pull request #5
Opened 2022-03-19 18:11 UTC by RuslanTyan

src/Brackets.php
Реализуйте функцию isBalanced(), которая принимает на вход строку, состоящую только из открывающих и закрывающих круглых скобок, и проверяет, является ли эта строка корректной. Пустая строка (отсутствие скобок) считается корректной.

Строка считается корректной (сбалансированной), если содержащаяся в ней скобочная структура соответствует требованиям:

Скобки — это парные структуры. У каждой открывающей скобки должна быть соответствующая ей закрывающая скобка.
Закрывающая скобка не должна идти впереди открывающей. Такой вариант недопустим )(, а вот такой допустим ()().
<?php

isBalanced('(())');  // true
isBalanced('((())'); // false

2022-03-21 08:13 UTC, ova777 requested changes
Всё отлично, только один лишний пробел "затесался".

2022-03-21 08:13 UTC, ova777 commented on src/Brackets.php
> +function isBalanced (string $str): ?bool
После названия функции не нужен пробел

2022-03-21 08:56 UTC, RuslanTyan commented on src/Brackets.php
> +function isBalanced (string $str): ?bool
fixed

2022-03-22 03:56 UTC, ova777 approved these changes

2022-03-22 04:34 UTC, merged