Challenge - 8 fizzBuzz function
RuslanTyan/phpcourse pull request #8
Opened 2022-03-24 07:37 UTC by RuslanTyan

Реализуйте функцию fizzBuzz(), которая выводит на экран числа в диапазоне от $begin до $end. При этом:

Если число делится без остатка на 3, то вместо него выводится слово Fizz
Если число делится без остатка на 5, то вместо него выводится слово Buzz
Если число делится без остатка и на 3, и на 5, то вместо числа выводится слово FizzBuzz
В остальных случаях выводится само число
Функция принимает два параметра ($begin и $end), определяющих начало и конец диапазона (включительно). Если диапазон пуст (в случае, когда $begin > $end), то функция просто ничего не печатает.

Пример
Вызов функции:

```
<?php

fizzBuzz(11, 20);
```
Вывод в терминале:

`11 Fizz 13 14 FizzBuzz 16 17 Fizz 19 Buzz`

2022-03-25 10:58 UTC, ova777 requested changes
Всё ок, но есть нюансы по оформлению.
Задача со "*" - сможешь сделать прям как в задании - что бы в конце не было "лишнего" пробела? ))

2022-03-25 10:58 UTC, ova777 commented on src/FizzBuzz.php
> +    if ($end < $begin) {
Действительно ли нужна эта проверка?

2022-03-25 10:58 UTC, ova777 commented on src/FizzBuzz.php
> +    return ($num % 3 === 0);
Это условие совсем не обязательно оборачивать в скобки (в isFifled тоже).

2022-03-25 10:58 UTC, ova777 commented on src/FizzBuzz.php
> +fizzBuzz(11,20);
Не хватает пробела после запятой

2022-03-25 11:32 UTC, RuslanTyan commented on src/FizzBuzz.php
> +    if ($end < $begin) {
елки-палки, точно, она же в for дублируется по сути

2022-03-25 18:44 UTC, RuslanTyan commented on src/FizzBuzz.php
> +    return ($num % 3 === 0);
убрал

2022-03-25 18:44 UTC, RuslanTyan commented on src/FizzBuzz.php
> +fizzBuzz(11,20);
поправил

2022-03-25 18:46 UTC, RuslanTyan commented on src/FizzBuzz.php
> +    if ($end < $begin) {
в следующей реализации эта проверка нужна, иначе каждую итерацию придется проверять не одно условие, а два.

2022-03-25 18:48 UTC, RuslanTyan commented
> Задача со "*" - сможешь сделать прям как в задании - что бы в конце не было "лишнего" пробела? ))

исправил

2022-03-28 12:13 UTC, ova777 approved these changes

2022-03-28 17:53 UTC, merged