Rtyan switch to classes
RuslanTyan/phpcourse pull request #9
Opened 2022-03-29 19:15 UTC by RuslanTyan

Move files to classes, used Exceptions

2022-04-04 06:49 UTC, ova777 requested changes

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/BinarySumViaInt.php
> +        $res = -(~bindec($substr) + 2 + PHP_INT_MAX);
Переменная $res излишняя, можно сразу return сделать

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/Brackets.php
> +            if ($depth < 0) return false;
Не должно быть в одну строку (взять в фигурные скобки)

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/Fibonacci.php
> +            throw new InvalidArgumentException("Error: function fib accepts only natural integer. \$index = $index was given");
Слишком длинная строка (более 120 символов)

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/Fibonacci.php
> +        return $fibCache[$index] = Fibonacci::fib($index - 1) + Fibonacci::fib($index - 2);
Есть же замечательное ключевое слово self (вместо Fibonacci)

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/Ticket.php
> +    function isHappy(string $ticketNumber): bool
Не хватает модификатора доступа

2022-04-04 06:49 UTC, ova777 commented on src/index.php
> +    $pr = new PerfectNumber;
При создании инстанса всегда нужно указывать скобки: `new PerfectNumber()`, даже если нет аргументов, в остальных местах аналогично

2022-04-04 06:49 UTC, ova777 commented on src/Tasks/BinarySum.php
> +    private function isBynaryString(string $str): bool
Переименуй пожалуйста Bynary в Binary (и в BinarySumViaInt тоже)

2022-04-04 07:56 UTC, RuslanTyan commented on src/Tasks/Fibonacci.php
> +        return $fibCache[$index] = Fibonacci::fib($index - 1) + Fibonacci::fib($index - 2);
мы его тогда еще не прошли :)

2022-04-04 07:57 UTC, RuslanTyan commented on src/Tasks/Brackets.php
> +            if ($depth < 0) return false;
🤦  опять (

2022-04-07 18:46 UTC, RuslanTyan commented on src/Tasks/BinarySum.php
> +    private function isBynaryString(string $str): bool
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/index.php
> +    $pr = new PerfectNumber;
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/Tasks/Ticket.php
> +    function isHappy(string $ticketNumber): bool
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/Tasks/Fibonacci.php
> +        return $fibCache[$index] = Fibonacci::fib($index - 1) + Fibonacci::fib($index - 2);
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/Tasks/Fibonacci.php
> +            throw new InvalidArgumentException("Error: function fib accepts only natural integer. \$index = $index was given");
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/Tasks/Brackets.php
> +            if ($depth < 0) return false;
поправил

2022-04-07 18:47 UTC, RuslanTyan commented on src/Tasks/BinarySumViaInt.php
> +        $res = -(~bindec($substr) + 2 + PHP_INT_MAX);
поправил

2022-04-20 05:07 UTC, ova777 requested changes

2022-04-20 05:07 UTC, ovaunit commented on src/Tasks/Fibonacci.php
> +        if (array_key_exists($index, self::$fibCache)) {
Здесь нет смысла использовать `array_key_exists`, проще воспользоваться `isset`:
```
isset(self::$fibCache[$index])
```

2022-04-20 05:07 UTC, ova777 commented on tests/Tasks/AddDigitsTests.php
> +            [PHP_INT_MAX, 7]
Забыл запятую в конце

2022-04-20 05:07 UTC, ova777 commented on tests/Tasks/BinarySumViaIntTest.php
> +            [decbin(PHP_INT_MAX) . '00','0'], //add double 0 because single 0 converts to negative binary only
Не хватает пробела после запятой

2022-04-20 05:07 UTC, ova777 commented on tests/Tasks/FibonacciTest.php
> +            [-1],
Если есть только один тесткейс - нет смысла в dataProvider, можно прямо этот кейс и проверить

2022-04-20 05:07 UTC, ova777 commented on tests/Tasks/TicketTest.php
> +    public function testIsHappy(string $number): void
Если ты тут тестируешь только положительные сценарии (а в testIsHappyNegative, по аналогии - негативные), то логичнее назвать тест testIsHappyPositive (и isHappyPositiveProvider - провайдер для него)

2022-04-20 05:07 UTC, ova777 commented on tests/Tasks/BracketsTest.php
> +        assertTrue($brackets->isBalanced($str) === $expected);
1. Забыл про self: `self::assertTrue`
2. Более подходящий assert здесь - assertEquals (`self::assertEquals($expected, $brackets->isBalanced($str))`), т.к. ты именно сравниваешь два значения (аналогично в testFizzBuzz, testIsPerfect и testIsPowerOfThree). Вот в TicketTest ты правильно воспользовался assertTrue и assertFalse.

2022-04-20 19:07 UTC, RuslanTyan commented on src/Tasks/Fibonacci.php
> +        if (array_key_exists($index, self::$fibCache)) {
пишут вроде, что с php 7.4 по скорости одинаковые они стали, но ок, переделаю 

> While Nik Tang's remark about the performance increase when using isset() first for PHP <= 7.3 is true, it is no longer valid for 7.4 and 8.0.
array_key_exists() is now as fast as isset() and the use of both is now slower for cases where the key is zero or actually does not exist.

2022-04-20 19:17 UTC, RuslanTyan commented on tests/Tasks/TicketTest.php
> +    public function testIsHappy(string $number): void
что-то я перемудрил тут, объединил и позитивные и негативные в один тест

2022-04-20 19:25 UTC, RuslanTyan commented on tests/Tasks/BracketsTest.php
> +        assertTrue($brackets->isBalanced($str) === $expected);
1. это я видимо экспериментировал с чтением документации phpUnit - https://phpunit.readthedocs.io/ru/latest/assertions.html?highlight=assertTrue#appendixes-assertions-static-vs-non-static-usage-of-assertion-methods :) 
там у меня импорт функции 
use function PHPUnit\Framework\assertTrue;
но наверное лучше одного стиля придерживаться - поправлю
2. поправлю

2022-04-20 19:38 UTC, RuslanTyan commented on tests/Tasks/TicketTest.php
> +    public function testIsHappy(string $number): void
поправил, как ты предложил,  сначала хотел объединить, но тогда у меня в тестах ни одного assertTrue не оставалось - не академично :)))

2022-04-20 19:41 UTC, RuslanTyan commented on tests/Tasks/BinarySumViaIntTest.php
> +            [decbin(PHP_INT_MAX) . '00','0'], //add double 0 because single 0 converts to negative binary only
интересно почему линтер на это не сругнулся 🤔

2022-04-20 19:49 UTC, RuslanTyan commented on tests/Tasks/FibonacciTest.php
> +            [-1],
поправил

2022-04-20 19:49 UTC, RuslanTyan commented on tests/Tasks/BinarySumViaIntTest.php
> +            [decbin(PHP_INT_MAX) . '00','0'], //add double 0 because single 0 converts to negative binary only
поправил

2022-04-20 19:49 UTC, RuslanTyan commented on tests/Tasks/AddDigitsTests.php
> +            [PHP_INT_MAX, 7]
поправил

2022-04-20 19:50 UTC, RuslanTyan commented on src/Tasks/Fibonacci.php
> +        if (array_key_exists($index, self::$fibCache)) {
поправил

2022-04-20 19:50 UTC, RuslanTyan commented on tests/Tasks/TicketTest.php
> +    public function testIsHappy(string $number): void
поправил

2022-04-20 19:51 UTC, RuslanTyan commented on tests/Tasks/BracketsTest.php
> +        assertTrue($brackets->isBalanced($str) === $expected);
поправил во всех местах где сравнивается с ожидаемым на assertEquals

2022-04-29 03:14 UTC, ova777 approved these changes

2022-04-29 05:26 UTC, merged